---
title: "Plotting rarefaction curves - LOB transects"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
# Set options, housekeeping
knitr::opts_chunk$set(
	echo = FALSE,
	include = TRUE,
	message = FALSE,
	warning = FALSE)
#rm(list=ls()) # Clear out environment if necessary
```

# Prerequisites
```{r message=FALSE, warning=FALSE, include=FALSE}
source("code/packages.R")
source("code/helper_functions.R")
load("data/Rdata/lob_predsum.Rdata")
load("data/Rdata/lob_preds.Rdata")
load("data/Rdata/lob_metadata.Rdata")
#source("code/diversity/transect_rarefaction.R")
```



# Introduction



We have 346 transects over 17 sites, with pretty even depth coverage:
```{r}
lob_metadata |> select(T_ID) |> distinct()
lob_metadata |> select(Site) |> distinct()
lob_metadata |> select(Depth) |> summary()
```


# Run rarefaction script
```{r}
source('code/diversity/transect_rarefaction.R')
```



## The files we need are buried in the raref object
```{r}
transect_rarefied$DataInfo
transect_rarefied$iNextEst$size_based
transect_rarefied$iNextEst$coverage_based 
transect_rarefied$AsyEst
```

# Extract just the asymptotic estimates

```{r}
asym_diversity <- 
  env_vars |> 
  right_join(transect_rarefied$AsyEst |> 
  rename(T_ID = Assemblage)) |>
  mutate_if(is.character, as.factor)
```



# Size based curves and estimates
```{r}
# Species richness
rarefied_q0_sizebased <- 
  env_vars |> 
  right_join(transect_rarefied$iNextEst$size_based |> 
  rename(T_ID = Assemblage)) |>
  mutate_if(is.character, as.factor) |> 
  filter(Order.q == 0)

# Shannon
rarefied_q1_sizebased <- 
  env_vars |> 
  right_join(transect_rarefied$iNextEst$size_based |> 
  rename(T_ID = Assemblage)) |>
  mutate_if(is.character, as.factor) |> 
  filter(Order.q == 1)
```
# Plots
## Species richness
```{r}
rarefied_q0_sizebased %>% 
  ggplot() +
  #geom_ribbon(aes(x = m, y = qD, ymin = qD.LCL, ymax = qD.UCL, fill = T_ID, colour = T_ID, group = T_ID), alpha = 0.3) +
  geom_line(data = . %>% filter(Method == "Rarefaction"), aes(x = m, y = qD, colour = T_ID, group = T_ID), size = 0.5) +
  geom_line(data = . %>% filter(Method == "Extrapolation"), aes(x = m, y = qD, colour = T_ID, group = T_ID), size = 0.5, lty = 11) +
  theme_minimal() +
  facet_wrap("Depth_bin") +
  theme(legend.position = "none")
```




# Coverage based estimates
```{r}
# Species richness
rarefied_q0_coveragebased <- 
  env_vars |> 
  right_join(transect_rarefied$iNextEst$coverage_based |> 
  rename(T_ID = Assemblage)) |>
  mutate_if(is.character, as.factor) |> 
  filter(Order.q == 0)

# Shannon
rarefied_q1_coveragebased <- 
  env_vars |> 
  right_join(transect_rarefied$iNextEst$coverage_based |> 
  rename(T_ID = Assemblage)) |>
  mutate_if(is.character, as.factor) |> 
  filter(Order.q == 1)
```



# Plots
## Sp rich
```{r}
rarefied_q0_coveragebased %>% 
  #filter(Region == "North") %>% 
  ggplot() +
  #geom_ribbon(aes(x = m, y = qD, ymin = qD.LCL, ymax = qD.UCL, fill = T_ID, colour = T_ID, group = T_ID), alpha = 0.3) +
  geom_line(aes(x = m, y = qD, colour = T_ID, group = T_ID), size = 0.5) +
  #geom_line(data = . %>% filter(Method == "Rarefaction"), aes(x = m, y = qD, colour = T_ID, group = T_ID), size = 0.5) +
  #geom_line(data = . %>% filter(Method == "Extrapolation"), aes(x = m, y = qD, colour = T_ID, group = T_ID), size = 0.5, lty = 11) +
  theme_minimal() +
  facet_wrap("Depth") +
  theme(legend.position = "none")
```

```{r}
# Shannon
rarefied_q1_coveragebased %>% 
  #filter(Region == "North") %>% 
  ggplot() +
  #geom_ribbon(aes(x = m, y = qD, ymin = qD.LCL, ymax = qD.UCL, fill = T_ID, colour = T_ID, group = T_ID), alpha = 0.3) +
  geom_line(aes(x = m, y = qD, colour = T_ID, group = T_ID), size = 0.5) +
  #geom_line(data = . %>% filter(Method == "Rarefaction"), aes(x = m, y = qD, colour = T_ID, group = T_ID), size = 0.5) +
  #geom_line(data = . %>% filter(Method == "Extrapolation"), aes(x = m, y = qD, colour = T_ID, group = T_ID), size = 0.5, lty = 11) +
  theme_minimal() +
  facet_wrap("Reef_1") +
  theme(legend.position = "none")
  
```



# Summary

# Save file
```{r}
lob_species_rich_asymp <- asym_diversity %>% 
  filter(Diversity == "Species richness") |> 
  rename(SpecRich = Estimator)
save(lob_species_rich_asymp, file = "data/Rdata/lob_species_rich_asymp.Rdata")
```





